#+TITLE: Curious Increase in Personal Computer Alternatives?
#+DATE: 2025-11-19
#+FILETAGS: :hardware:personal-computing:developer-tools:terminal:

I came across the [[https://caligra.com/][Caligra c100 Developer Terminal]] (see related [[https://news.ycombinator.com/item?id=44810847][Hacker News discussion]]) recently, and it got me thinking about where we are in the evolution of personal computing. The landing page is extremely sparse with just a $99 pre-order button for a product supposedly shipping as early as January 2026. It almost seems like a veiled cash grab given how little information is actually provided. I'm only writing about it because the "mockup" (if it even is one) looks interesting, reminiscent of old terminal computers from the 80s and 90s. It says it runs [[https://caligra.com/workbench/][Workbench]], presumably a custom Linux distribution based on Fedora, though once again there's a shocking lack of concrete details.

Still, the whole thing makes me wonder: are we on the cusp of a new personal computer era? There seems to be real appetite for easy-to-use, open systems that aren't tied to Apple, Microsoft, or Google.

Take [[https://radiant.computer/][Radiant Computer]] (see related [[https://news.ycombinator.com/item?id=45822559][Hacker News discussion]]), which presents a ground-up reimagining of the personal computer from the OS, userland, to almost everything. It's extremely ambitious: a new OS with a custom low-level language (R') and general-purpose language (R, unfortunately not to be confused with the statistical programming language). The name collision alone concerns me. That said, the creator's choice of RISC-V as the underlying architecture is smart. It's open and has a growing ecosystem.

The barrier to entry for Linux has been steadily dropping as well. DHH's [[https://omarchy.org/][Omarchy]] is getting strange traction among traditionally non-Linux users with its Arch/Hyprland configuration, trying to prove that even notoriously hands-on distros can be used by beginners with the right defaults. Though this feels almost culty at times.

I guess what I'm trying to indicate is that I'm seeing an increase attention on personal computing alternatives. Though I'm not sure if it's just my own bubble or my own focus creating a confirmation bias. I'd like to see ideas realized here. I want highly configurable yet approachable personal computers. I want hardware integration on the level of Apple without their closed ecosystem. I want attractive industrial design. I want performance without bloat. I don't want surveillance and ad-tech baked in. I don't know if that's through Linux or not, but the broader population, those outside of tech even inside too if I'm being honest, seem to choose the option of least resistence. Windows is still byfar the most dominant operating system. MacOS while intrinsically better than Windows forces user's into the Apple ecosystem. I want more options.
