import { readFileSync, writeFileSync } from 'fs';
import Parser from 'rss-parser';
import { stringify } from 'yaml';

type BlogrollPost = {
	title: string;
	url: string;
	date: string;
	domain: string;
	feed_url: string;
};

async function fetchFeed(feedUrl: string, maxPosts: number = 3): Promise<BlogrollPost[]> {
	const parser = new Parser();

	try {
		console.log(`Fetching feed: ${feedUrl}`);
		const feed = await parser.parseURL(feedUrl);

		const posts: BlogrollPost[] = [];
		const items = feed.items.slice(0, maxPosts);

		for (const item of items) {
			const domain = new URL(feedUrl).hostname;
			const dateStr = item.isoDate || item.pubDate || new Date().toISOString();
			const date = new Date(dateStr);

			posts.push({
				title: item.title || 'Untitled',
				url: item.link || '',
				date: date.toISOString().split('T')[0],
				domain,
				feed_url: feedUrl
			});
		}

		console.log(`Retrieved ${posts.length} posts from ${feedUrl}`);
		return posts;
	} catch (error) {
		console.error(`Error fetching ${feedUrl}:`, error);
		return [];
	}
}

async function generateBlogroll() {
	const blogrollFile = 'static/assets/blogroll.txt';
	const outputFile = 'src/lib/data/blogroll.yaml';

	// Read feed URLs
	const content = readFileSync(blogrollFile, 'utf-8');
	const feedUrls = content
		.split('\n')
		.map((line) => line.trim())
		.filter((line) => line && !line.startsWith('#'));

	console.log(`Found ${feedUrls.length} feed URLs to process`);

	// Fetch all feeds
	const allPosts: BlogrollPost[] = [];
	for (const feedUrl of feedUrls) {
		const posts = await fetchFeed(feedUrl, 3);
		allPosts.push(...posts);
	}

	// Sort by date (newest first)
	allPosts.sort((a, b) => {
		return new Date(b.date).getTime() - new Date(a.date).getTime();
	});

	// Generate YAML with comment header
	const now = new Date();
	const header = `# Generated by blogroll-generator
# Generated on: ${now.toISOString().replace('T', ' ').split('.')[0]}

`;

	const yamlContent = stringify(allPosts);
	writeFileSync(outputFile, header + yamlContent, 'utf-8');

	console.log(`Wrote ${allPosts.length} total posts to ${outputFile}`);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
	generateBlogroll().catch((error) => {
		console.error('Error generating blogroll:', error);
		process.exit(1);
	});
}

export { generateBlogroll };
