#!/usr/bin/env tsx

import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

/**
 * Generate version file from git tag or package.json
 * Prefers git tag, falls back to package.json version
 */
export function generateVersion() {
	let version = 'v0.0.0';

	try {
		// Try to get version from git tag
		const gitVersion = execSync('git describe --tags --abbrev=0', {
			encoding: 'utf-8',
			stdio: ['pipe', 'pipe', 'ignore']
		}).trim();

		if (gitVersion) {
			version = gitVersion;
			console.log(`  Using git tag: ${version}`);
		}
	} catch {
		// Fall back to package.json version
		try {
			const packagePath = join(process.cwd(), 'package.json');
			const packageJson = JSON.parse(readFileSync(packagePath, 'utf-8'));
			version = `v${packageJson.version}`;
			console.log(`  Using package.json: ${version}`);
		} catch {
			console.warn(`  Warning: Could not read version, using default: ${version}`);
		}
	}

	// Generate TypeScript file
	const content = `// This file is auto-generated by scripts/generate-version.ts
// Do not edit manually - changes will be overwritten

export const VERSION = '${version}';
`;

	const outputPath = join(process.cwd(), 'src', 'lib', 'version.ts');
	writeFileSync(outputPath, content, 'utf-8');
	console.log(`  Written to: src/lib/version.ts`);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
	generateVersion();
}
