package main

import (
	"fmt"
	"log"
	"os"
	"sort"
	"time"

	"github.com/natrimmer/synthetic.software/tools/internal/config"
	"github.com/natrimmer/synthetic.software/tools/internal/feeds"
)

func main() {
	inputFile := "static/assets/blogroll.txt"

	if len(os.Args) > 1 {
		inputFile = os.Args[1]
	}

	urls, err := config.ReadURLs(inputFile)
	if err != nil {
		log.Fatalf("Error reading URLs from %s: %v", inputFile, err)
	}

	var allPosts []feeds.Post

	for _, feedURL := range urls {
		posts, err := feeds.FetchAndParse(feedURL, 3)
		if err != nil {
			log.Printf("Error processing %s: %v", feedURL, err)
			continue
		}
		allPosts = append(allPosts, posts...)
	}

	sort.Slice(allPosts, func(i, j int) bool {
		return allPosts[i].PubDate.After(allPosts[j].PubDate)
	})

	writeYAML(allPosts)
}

func writeYAML(posts []feeds.Post) {
	// Write metadata comments
	fmt.Println("# Generated by blogroll-generator")
	fmt.Printf("# Generated on: %s\n", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Println()

	// Write posts
	for _, post := range posts {
		fmt.Printf("- title: %q\n", post.Title)
		fmt.Printf("  url: %q\n", post.URL)
		fmt.Printf("  date: %q\n", post.Date)
		fmt.Printf("  domain: %q\n", post.Domain)
		fmt.Printf("  feed_url: %q\n", post.FeedURL)
	}
}
